<a href="https://colab.research.google.com/github/anniiexp/MAT422/blob/main/1_2_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MAT422 - Section 1.2: Linear Algebra in Python
---

### Topics:

*   Linear spaces
*   Orthogonality


*   Gram-Schmidt process
*   Eigenvalues and eigenvectors





In [51]:
import numpy as np
import matplotlib.pyplot as plt

np.set_printoptions(precision=4, suppress=True)

## 1.2.1 Linear Spaces

A linear space is a set of objects, vectors, that you can add together and scale by numbers (scalars) and the results stay inside the same set.
For example, a set V is a vector space if for any vectors u, v in V and any scalar c:


*   $u + v$ is still in V
*   $c \cdot u$ is still in V



In [52]:
u = np.array([1, 2, 3])
v = np.array([4, -1, 2])
c = 2.5

# closure under addition
sum = u + v
print("u + v =", sum)

# closure under scalar multipication
scaled_u = c * u
print("c * u =", scaled_u)


u + v = [5 1 5]
c * u = [2.5 5.  7.5]


There is also the zero vector, additive inverse, and linear combination. Adding the zero vector to any vector leaves the original vector unchanged. Every vector u has an inverse (-u) which means it can cancel out the original vector. Lastly, scaling and adding vectors together like below (2u + 2v) produces a new vector that falls within the span of the original vectors.

In [53]:
# zero vector
zero = np.zeros(3)
print("u + 0 =", u + zero)

# additive inverse
neg_u = -u
print("u + (-u) =", u + neg_u)

# linear combination
comb = 2*u + 2*v
print("2u + 2v =", comb)

u + 0 = [1. 2. 3.]
u + (-u) = [0 0 0]
2u + 2v = [10  2 10]


These properties work with matrices as well

In [54]:
A = np.array([[1, 2], [3, 4]], dtype=float)
B = np.array([[0, -1], [2, 5]], dtype=float)
c = 3

print("A =\n", A)
print("B =\n", B)
print("A + B =\n", A + B)
print("c * A =\n", c * A)

A =
 [[1. 2.]
 [3. 4.]]
B =
 [[ 0. -1.]
 [ 2.  5.]]
A + B =
 [[1. 1.]
 [5. 9.]]
c * A =
 [[ 3.  6.]
 [ 9. 12.]]


## 1.2.2 Orthogonality

Orthogonality means two vectors are perpendicular. The vectors are orthogonal if their dot product equals 0. This means that neither vector has any component "in the direction" of the other.

In [55]:
M = np.array([[1, 2, 0, 3],
              [2, -1, 4, 1],
              [0, 3, 0, -2],
              [1, 1, -1, 0]], dtype=float)

u = M[:, 0]
v = M[:, 1]

# dot product
dot_p = np.dot(u, v)
print("u . v =", dot_p)

# norms (magnitudes)
norm_u = np.linalg.norm(u)
norm_v = np.linalg.norm(v)
print("||u|| =", norm_u)
print("||v|| =", norm_v)

# angle between u and v with cosine
cos_theta = np.dot(u, v) / (norm_u * norm_v)
theta = np.degrees(np.arccos(cos_theta))
print("the angle between u and v (degrees) =", theta)

# projection of u onto v
proj = (np.dot(u, v) / np.dot(v, v)) * v
print("projection of u onto v =", proj)

u . v = 1.0
||u|| = 2.449489742783178
||v|| = 3.872983346207417
the angle between u and v (degrees) = 83.94925398408826
projection of u onto v = [ 0.1333 -0.0667  0.2     0.0667]


The next example is showing the vectors that are mathematically orthogonal even through rotation or normalization. The floating point math usually leaves a remainder instead of exact 0.

In [56]:
# demonstrating floating point roundoff
a = np.array([1, 1], dtype=float)
b = np.array([1, -1], dtype=float)

# rotate b using trig functions
theta = np.pi / 2
rotated_matrix = np.array([[np.cos(theta), -np.sin(theta)],
                     [np.sin(theta), np.cos(theta)]])
b_rotated = rotated_matrix @ a

dot_result = np.dot(a, b_rotated)
print("dot product after rotation =", dot_result)
print("is it exactly zero?", dot_result == 0)
print("is it close to zero?", np.isclose(dot_result, 0))

dot product after rotation = 1.1102230246251565e-16
is it exactly zero? False
is it close to zero? True


## 1.2.3 Gram-Schmidt process

Gram-Schmidt takes linearly independent vectors and turn them into an orthonormal basis, where vectors are orthogonal and have the length of 1. We can take a vector one at a time, and subtract it's projection on the vectors.

In [57]:
# Gram-Schmidt on 3 linearly independent vectors
a1 = np.array([1, 1, 0], dtype=float)
a2 = np.array([1, 0, 1], dtype=float)
a3 = np.array([0, 1, 1], dtype=float)

def project(u, v):
  # projection of u and v
  proj = np.dot(v, u) / np.dot(u, u) * u
  return proj

vector1 = a1 / np.linalg.norm(a1)

b2 = a2 - project(vector1, a2)
vector2 = b2 / np.linalg.norm(b2)

b3 = a3 - project(vector1, a3) - project(vector2, a3)
vector3 = b3 / np.linalg.norm(b3)

print("q1 =", vector1)
print("q2 =", vector2)
print('q3 =', vector3)

# verify if orthonmal
print("vector1 . vector2 =", np.dot(vector1, vector2))
print("vector1 . vector3 =", np.dot(vector1, vector3))
print("vector2 . vector3 =", np.dot(vector2, vector3))
print("||vector1|| =", np.linalg.norm(vector1))
print("||vector2|| =", np.linalg.norm(vector2))
print("||vector3|| =", np.linalg.norm(vector3))

q1 = [0.7071 0.7071 0.    ]
q2 = [ 0.4082 -0.4082  0.8165]
q3 = [-0.5774  0.5774  0.5774]
vector1 . vector2 = 0.0
vector1 . vector3 = 0.0
vector2 . vector3 = 1.1102230246251565e-16
||vector1|| = 0.9999999999999999
||vector2|| = 1.0
||vector3|| = 0.9999999999999998


The resulting vectors vector1, vector2, vector3 are mutually orthogonal (their dot products are 0) and each as a norm of 1 which shows they form an orthonormal basis. Even though vector2 * vector3 and ||vector|| show floating point remainders, this is an expected roundoff error.

## 1.2.4 Eigenvalues and eigenvectors


An eigenvector of a matrix A is a vector that doesn't change direction when A is applied to it. It's only scaled by the factor eigenvalue. This function is written as $Av = \lambda v$. Eigenvalues and eigenvectors show the directions in which a linear transformation acts as it's either stretching or shrinking.

In [58]:
# eigenvalues and eigenvectors of a symmetric matrix
A = np.array([[0.7, 0.2],
              [0.3, 0.8]], dtype=float)

eigenvalues, eigenvectors = np.linalg.eig(A)

print("A =\n", A)
print("eigenvalues =", eigenvalues)
print("eigenvectors =", eigenvectors)

for i in range(len(eigenvalues)):
  lam = eigenvalues[i]
  v = eigenvectors[:, i]
  residual = A @ v - lam * v
  residual_norm = np.linalg.norm(residual)
  print(f"\nEignepair {i+1}: lambda = {lam}, v = {v}")
  print("Residual norm ||Av - lambda v|| =", residual_norm)

vector1 = eigenvectors[:, 0]
vector2 = eigenvectors[:, 1]
print("\nvector1 . vector2 =", np.dot(vector1, vector2))


A =
 [[2. 1.]
 [1. 2.]]
eigenvalues = [3. 1.]
eigenvectors = [[ 0.7071 -0.7071]
 [ 0.7071  0.7071]]

Eignepair 1: lambda = 3.0, v = [0.7071 0.7071]
Residual norm ||Av - lambda v|| = 0.0

Eignepair 2: lambda = 1.0, v = [-0.7071  0.7071]
Residual norm ||Av - lambda v|| = 0.0

vector1 . vector2 = 0.0


Each eigenvector points in a direction that A only stretches or shrinks (scales by eigenvalue) without rotation. Since A is symmetric, its eigenvectors are also orthogonal to each other, which is shown by the dot product of vector1 and vector 2.

## Reflection

- **Linear spaces**: showed closure under addition and scalar multiplication using vectors and matrices, along with the zero vector, additive inverse, and a linear combination.
- **Orthogonality**: computed dot products, norms, angles, and projections, and demonstrated how floating-point roundoff affects if  orthogonal or not.
- **Gram-Schmidt process**: converted a set of linearly independent vectors into an orthonormal basis and verified orthonormality.
- **Eigenvalues and eigenvectors**: computed eigenpairs for a matrix and verified Av = λv using residual norms and computed with shrinking and stretching with the eigenvalue.